#!/bin/bash

set -e

build_mode=${1:-"development"}
lambda_name="ajf-live-re-wire"
if [ "$build_mode" == "development" ]; then
    lambda_name="oz-re-wire"
fi

sudo docker build -t $lambda_name .

account_id=$(aws sts get-caller-identity --query Account --output text)

sudo docker tag $lambda_name:latest $account_id.dkr.ecr.us-east-1.amazonaws.com/$lambda_name:latest

sudo docker push $account_id.dkr.ecr.us-east-1.amazonaws.com/$lambda_name:latest

aws lambda update-function-code --function-name $lambda_name --image-uri $account_id.dkr.ecr.us-east-1.amazonaws.com/$lambda_name:latest
