#!/bin/bash

set -e

# Ensure we're in the project root directory
PROJECT_ROOT=$(pwd)

# Create a temporary directory for packaging
TEMP_DIR=$(mktemp -d)

# Install dependencies
echo "Installing dependencies..."
pipenv install --deploy --ignore-pipfile

# Copy project files to temp directory
echo "Copying project files..."
cp -R main.py tests $TEMP_DIR/

# Copy dependencies
echo "Copying dependencies..."
SITE_PACKAGES=$(pipenv --venv)/lib/python$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")/site-packages
cp -R $SITE_PACKAGES/* $TEMP_DIR/

# Remove unnecessary files
echo "Removing unnecessary files..."
find $TEMP_DIR -type d -name "__pycache__" -exec rm -rf {} +
find $TEMP_DIR -type d -name "*.dist-info" -exec rm -rf {} +
find $TEMP_DIR -type d -name "*.egg-info" -exec rm -rf {} +

# Create the zip file
echo "Creating zip file..."
cd $TEMP_DIR
zip -r9 $PROJECT_ROOT/CICD/lambda_function_payload.zip .

# Clean up
cd $PROJECT_ROOT
rm -rf $TEMP_DIR

echo "Package created at $PROJECT_ROOT/CICD/lambda_function_payload.zip"

# Uncomment the following line to upload to AWS Lambda
# aws lambda update-function-code --function-name oz-re-wire --zip-file fileb://CICD/lambda_function_payload.zip
